apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: counter-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: counter
spec:
  hosts:
  - "*"
  gateways:
  - counter-gateway
  http:
  - match:
    - uri:
        exact: /counter
    - uri:
        exact: /counter/main
    - uri:
        exact: /counter/get   
    - uri:
        exact: /counter/roll   
    - uri:
        exact: /counter/reset   
    route:
    - destination:
        host: main-python-service
        subset: v1
        port:
          number: 5000
      weight: 10
    - destination:
        host: main-python-service
        subset: v2
        port:
          number: 5000
      weight: 90 
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: main-python-service
spec:
  host: main-python-service
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2